package com.example.librarymanagementsystem.Models;

import com.example.librarymanagementsystem.Enums.Department;
import com.example.librarymanagementsystem.Enums.Gender;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name="student")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Student {

    @Id //Used for saying it as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Due to this rollNo will autogenerated in increasing order
    private Integer rollNo;

    private String name;

    private Integer age;

    @Enumerated(value = EnumType.STRING)
    private Gender gender; //This gender is of user defined datatype: this takes only values provided in gender enum class

    @Enumerated(value = EnumType.STRING) // helps system to think enum as string datatype but not any custom datatype
    private Department department;

    @Column(unique = true)
    private String email;

    //Below syntax is for Bi directional mapping to be written in parent class
    @OneToOne(mappedBy = "student", cascade = CascadeType.ALL)
    private LibraryCard card;
}
